### ISSUE TITLE
being able to add more than one friend at once on compare.html

### ISSUE THREAD

**Issue by tiffanynwyeung** [NATHAN4/WatWhenWhere#28] opened 2016-01-02 05:49 UTC
it'd be way easier to do that than going back and having to expend extra effort to search for friends

**Comment by nwoodthorpe** [comment] 2016-01-02 19:29
We'll fix this today!

Duplicate of [#6](https://github.com/NATHAN4/WatWhenWhere/issues/6).

**Closed as completed by nwoodthorpe** 2016-01-02 19:29 UTC
