### ISSUE TITLE
Empty search for friends gives you whole list

### ISSUE THREAD

**Issue by tiffanynwyeung** [NATHAN4/WatWhenWhere#26] opened 2016-01-02 05:23 UTC
Probably should have a "cannot be found, try again" sort of thing.

Also, this part isn't so much a bug: keysmashing a query gives you a list regardless, as shown in this pic:
![image](https://cloud.githubusercontent.com/assets/8635193/12073317/e14fcf26-b0e6-11e5-8992-063d15e71f87.png)

**Comment by nwoodthorpe** [comment] 2016-01-02 17:30
Duplicate of issue [#21](https://github.com/NATHAN4/WatWhenWhere/issues/21) , fixing now!

**Closed as completed by nwoodthorpe** 2016-01-02 17:30 UTC
